name: IOS Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_26.0.1.app
        
      - name: Prepare TestResults folder
        run: mkdir -p TestResults
        
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
    
      - name: Build and Test
        run: |
          xcodebuild clean build test \
            -project EPCollaboratif.xcodeproj \
            -scheme EPCollaboratif \
            -destination 'platform=iOS Simulator,name=iPhone 17 Pro,OS=26.0.1' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
            -enableThreadSanitizer YES \
            ONLY_ACTIVE_ARCH=YES \
            -resultBundlePath TestResults/TestResults.xcresult
            
      - name: Check xcresult folder after build
        run: ls -la TestResults/
        
      - name: List contents of xcresult
        run: xcrun xcresulttool get object --legacy --path TestResults/TestResults.xcresult --format json

      - name: Process Test Results
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults/TestResults.xcresult
        if: success() || failure()
