name: IOS Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clean previous test results
        run: rm -rf TestResults
        
      - name: List available simulators
        run: xcrun simctl list devices
    
      - name: Build and Test
        uses: sersoft-gmbh/xcodebuild-action@v3.2.0
        with:
            project: EPCollaboratif.xcodeproj
            scheme: EPCollaboratif
            destination: 'platform=iOS Simulator,name=iPhone 14,OS=17.0'
            action: test
            result-bundle-path: 'TestResults/TestResults.xcresult'
            
      - name: Check xcresult folder
        run: ls -la TestResults/
            
      - name: Inspect Test Results
        run: xcrun xcresulttool get object --path TestResults/TestResults.xcresult --format json
